name: rental_car_app
description: App de alquiler de vehÃ­culos con Flutter y Firebase
publish_to: 'none'
version: 1.1.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  
  # Date Handling
  intl: ^0.19.0
  table_calendar: ^3.1.2
  
  # State Management
  provider: ^6.1.2
  
  # Utilities
  uuid: ^4.5.1
  image_picker: ^0.8.7+6
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  
  # Update System
  dio: ^5.3.0
  package_info_plus: ^4.0.0
  path_provider: ^2.1.0
  
  # Performance & Caching
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  get_it: ^7.6.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/